---

- name: Git clone
  git:
    repo: https://github.com/laravel/laravel
    dest: /var/www/laravel
    update: no

- name: Генерация конфигурационного файла .env из шаблона
  template:
    src: env.j2
    dest: /var/www/laravel/.env

- name: Composer
  composer:
    command: install
    working_dir: /var/www/laravel
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Start laravel
  shell: |
    cd /var/www/laravel
    php artisan key:generate
    php artisan migrate
    chown -R www-data:www-data /var/www/laravel
    chmod -R 755 /var/www/laravel
    chmod -R 644 /var/www/laravel/public/*
