---

- name: Add Python module PyMySQL for Ansible
  pip:
    name: PyMySQL
    state: present

- name: Create new DB
  mysql_db:
    name: "{{ DB_DATABASE }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create new user MySQL
  mysql_user:
    name: "{{ DB_USERNAME }}"
    password: "{{ DB_PASSWORD }}"
    priv: "{{ DB_DATABASE }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Check permissions new user MySQL
  mysql_user:
    name: "{{ DB_USERNAME }}"
    append_privs: yes
    priv: "{{ DB_DATABASE }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
