---

- name: Генерация конфигурационного файла default из шаблона
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  register: nginxreload1

- name: Генерация конфигурационного файла nginx.conf из шаблона
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/nginx.conf
  register: nginxreload2

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  when: nginxreload1.changed or nginxreload2.changed

- name: Start mysql
  service:
    name: mysql
    state: started 

- name: Start php-fpm8.3
  service:
    name: php8.3-fpm
    state: started

